#!/usr/bin/env bash
# Manages the manage_my_process script.
#   When passed the argument `start`:
#     1. Begins manage_my_process script
#     2. Creates a file containing PID in /var/run/my_process.pid
#     3. Displays "manage_my_process started"
#   When passed the argument `stop`:
#     1. Ends manage_my_process
#     2. Deletes the /var/run/my_process.pid file
#     3. Displays "manage_my_process stopped"
#   When passed the argument `restart`:
#     1. Ends manage_my_process
#     2. Deletes the /var/run/my_process.pid file
#     3. Begins manage_my_process
#     4. Creates a file containing PID in /var/run/my_process.pid
#     5. Shows "manage_my_process restarted"
#   If any other or no arguments are passed, Shows
#+  "Usage: manage_my_process {start|stop|restart}"

if [ "${1}" == "start" ]
then
    ./manage_my_process &
    touch /var/run/my_process.pid
    echo "$!" > /var/run/my_process.pid
    echo "manage_my_process started"
elif [ "${1}" == "stop" ]
then
    echo "manage_my_process stopped"
    kill "$(cat /var/run/my_process.pid)"
    rm /var/run/my_process.pid
elif [ "${1}" == "restart" ]
then
    kill "$(cat /var/run/my_process.pid)"
    rm /var/run/my_process.pid
    ./manage_my_process &
    touch /var/run/my_process.pid
    echo "$!" > /var/run/my_process.pid
    echo "manage_my_process restarted"
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
